pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label="1 merge queue"
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    batch_size: 3
    conditions:
      - label="fake check merge"
